const baseConfigFormData = [
    {
        label:"标题设置",
        child:[
            {label:"标题名称",type:"input",modeKey:"titleName",need:false},
            {label:"字体颜色",type:"fontInput",modeKey:"titleFontColor",need:false},
            {label:"字体大小",type:"number",modeKey:"titleFontSize",need:false},
            {label:"字体位置",type:"select",modeKey:"titleTextAlign",need:false,multiple:false},
            {label:"字体粗细",type:"select",modeKey:"titlefontWeight",need:false,multiple:false},
            {label:"字体间距",type:"sliderRange",modeKey:"titleLetterSpacing",need:false},
            {label:"排列方式",type:"select",modeKey:"titleArrayType",need:false,multiple:false},
        ]
    },
    {
        label:"基本设置",
        child:[
            {label:"轮播开关",type:"switch",modeKey:"basicSwitch",need:false},
            {label:"形状",type:"select",modeKey:"basicShape",need:false,multiple:false},
            {label:"展示方式",type:"radioGroup",modeKey:"basicViewModel",need:false},
            {label:"堆叠",type:"switch",modeKey:"barStackSwitch",need:false},
            {label:"柱体宽度",type:"sliderRange",modeKey:"basicBarWidth",need:false},
            {label:"类型",type:"radioGroup",modeKey:"progressType",need:false},
            {label:"颜色",type:"fontInput",modeKey:"barBGColor",need:false},
            {label:"背景颜色",type:"fontInput",modeKey:"basicBGColor",need:false},

            {label:"连线模式",type:"radioGroup",modeKey:"lineModel",need:false},
            {label:"面积堆积",type:"switch",modeKey:"areaStackSwitch",need:false},
            {label:"点大小",type:"sliderRange",modeKey:"pointSize",need:false},
            
            
            {label:"视频地址",type:"input",need:false,modeKey:"basicVideo"},
            {label:"图片添加",type:"addImage",need:false,modeKey:"basicImage"},
            {label:"组件尺寸",type:"areaSize",need:false,modeKey:"basicArea"},
            {label:"组件位置",type:"areaSize",need:false,modeKey:"basicPosition"},
            {label:"文本内容",type:"input",modeKey:"textContent",need:false},
            {label:"最大字号",type:"number",modeKey:"minFontSize",need:false},
            {label:"最小字号",type:"number",modeKey:"maxFontSize",need:false},
            
            {label:"字体颜色",type:"fontInput",modeKey:"basicFontColor",need:false},
            {label:"字体大小",type:"number",modeKey:"basicFontSize",need:false},
            {label:"字体粗细",type:"select",modeKey:"basicfontWeight",need:false,multiple:false},
            {label:"跑马灯模式",type:"switch",modeKey:"lampSwitch",need:false},
            {label:"自动播放",type:"switch",modeKey:"autoPlaySwitch",need:false},
            {label:"循环播放",type:"switch",modeKey:"loopPLaySwitch",need:false},
            {label:"滚动速度",type:"number",modeKey:"scrollSpeed",need:false},
            
            {label:"时间格式",type:"select",modeKey:"timeFormat",need:false,multiple:false},
            {label:"文字间距",type:"sliderRange",modeKey:"letterSpacing",need:false},
        ]
    },
    {
        label:"XY轴设置",
        child:[
            {label:"表头名称",type:"inputList",need:false,modeKey:"axisName"},
            {label:"字体大小",type:"number",modeKey:"",need:false},
            {label:"X轴网格线",type:"switch",modeKey:"XSplitLine",need:false},
            {label:"Y轴网格线",type:"switch",modeKey:"YSplitLine",need:false},
            {label:"网格线颜色",type:"fontInput",modeKey:"SplitColor",need:false},
            {label:"轴字体大小",type:"number",modeKey:"axisFontSize",need:false},
            {label:"轴字体颜色",type:"fontInput",modeKey:"axisFontColor",need:false},
        ]
    },
    {
        label:"数值设置",
        child:[
            {label:"显示开关",type:"switch",modeKey:"numberSwitch",need:false},
            {label:"字体颜色",type:"fontInput",modeKey:"numberFontColor",need:false},
            {label:"字体大小",type:"number",modeKey:"numberFontSize",need:false},
        ]
    },
    {
        label:"系列",
        type:"series",
        child:[
            {label:"添加系列",type:"seriesList",modeKey:"addSeries",need:false},
        ]
    },
    {
        label:"图例",
        child:[
            {label:"显示开关",type:"switch",modeKey:"legendSwitch",need:false},
            {label:"图例样式",type:"select",modeKey:"legendIcon",need:false,multiple:false},
            {label:"图例位置",type:"select",modeKey:"legendPosition",need:false,multiple:false},
            {label:"字体大小",type:"number",modeKey:"legendFontSize",need:false},
            {label:"字体颜色",type:"fontInput",modeKey:"legendFontColor",need:false},
        ]
    },
    {
        label:"前缀",
        child:[
            {label:"内容",type:"input",modeKey:"prefixName",need:false},
            {label:"字体颜色",type:"fontInput",modeKey:"prefixFontColor",need:false},
            {label:"字体大小",type:"number",modeKey:"prefixFontSize",need:false},
            {label:"字体粗细",type:"select",modeKey:"prefixfontWeight",need:false,multiple:false},
            {label:"字体间距",type:"sliderRange",modeKey:"prefixLetterSpacing",need:false},
        ]
    },
    {
        label:"数字",
        child:[
            {label:"字体颜色",type:"fontInput",modeKey:"loopNumFontColor",need:false},
            {label:"字体大小",type:"number",modeKey:"loopNumFontSize",need:false},
            {label:"字体粗细",type:"select",modeKey:"loopNumfontWeight",need:false,multiple:false},
            {label:"千位分隔符",type:"switch",modeKey:"loopNumSeparator",need:false},
        ]
    },
    {
        label:"后缀",
        child:[
            {label:"内容",type:"input",modeKey:"SuffixName",need:false},
            {label:"字体颜色",type:"fontInput",modeKey:"SuffixFontColor",need:false},
            {label:"字体大小",type:"number",modeKey:"SuffixFontSize",need:false},
            {label:"字体粗细",type:"select",modeKey:"SuffixfontWeight",need:false,multiple:false},
            {label:"字体间距",type:"sliderRange",modeKey:"SuffixLetterSpacing",need:false},
        ]
    },
    {
        label:"信息",
        child:[
            {label:"字体位置",type:"select",modeKey:"infoTextAlign",need:false,multiple:false},
            {label:"字体颜色",type:"fontInput",modeKey:"infoFontColor",need:false},
            {label:"字体大小",type:"number",modeKey:"infoFontSize",need:false},
            {label:"字体间距",type:"sliderRange",modeKey:"infoLetterSpacing",need:false},
        ]
    },
    {
        label:"表头",
        type:"gridHeader",
        child:[
            {label:"添加系列",type:"headerList",modeKey:"addheader",need:false},
        ]
    },
    {
        label:"表头设置",
        child:[
            {label:"字体颜色",type:"fontInput",modeKey:"headerFontColor",need:false},
            {label:"字体大小",type:"number",modeKey:"headerFontSize",need:false},
            {label:"字体间距",type:"sliderRange",modeKey:"headerLetterSpacing",need:false},
        ]
    },
];
export default baseConfigFormData;
